# fly.toml app configuration file generated for bugtracker-backend-dominik-adamczewski on 2025-11-02T07:57:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bugtracker-backend-dominik-adamczewski'
primary_region = 'fra'

[build]

[mounts]
  source="bugtracker_data"
  destination="/data"

[env]
  DB_PATH = "/data/bugs.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
